import Head from 'next/head'
import styles from './Layout.module.css'

export default function Layout({children, title="world rank" }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title  }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <header>
            <img height="100" width="100" src="https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png"/>    
        </header>
      <main className={styles.main}>
        {children}
      </main>

      <footer className={styles.footer}>
        Footer
      </footer>
    </div>
  )
}
